2020-12-30 14:23:21.874 - INFO - 4032 - azureml.train.automl.automlconfig._start_execution:152 - No compute target or run config provided. Running local legacy run.
2020-12-30 14:23:22.888 - INFO - 4032 - azureml.train.automl.automlconfig._start_execution:195 - Submitting local legacy run.
2020-12-30 14:23:22.892 - INFO - 4032 - azureml.automl.core.package_utilities._log_activity:54 - ActivityStarted: PackagesCheck
2020-12-30 14:23:22.922 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: ipywidgets, Version: 7.5.1 found.
2020-12-30 14:23:22.923 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-telemetry, Version: 1.19.0 found.
2020-12-30 14:23:22.923 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-core, Version: 1.19.0 found.
2020-12-30 14:23:22.923 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-core, Version: 1.19.0 found.
2020-12-30 14:23:22.924 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: applicationinsights, Version: 0.11.9 found.
2020-12-30 14:23:22.924 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-telemetry, Version: 1.19.0 found.
2020-12-30 14:23:22.924 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-train-restclients-hyperdrive, Version: 1.19.0 found.
2020-12-30 14:23:22.924 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-core, Version: 1.19.0 found.
2020-12-30 14:23:22.924 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-dataset-runtime, Version: 1.19.0.post1 found.
2020-12-30 14:23:22.925 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-telemetry, Version: 1.19.0 found.
2020-12-30 14:23:22.925 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-automl-core, Version: 1.19.0 found.
2020-12-30 14:23:22.925 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-dataset-runtime, Version: 1.19.0.post1 found.
2020-12-30 14:23:22.925 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-telemetry, Version: 1.19.0 found.
2020-12-30 14:23:22.925 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-core, Version: 1.19.0 found.
2020-12-30 14:23:22.928 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-train-core, Version: 1.19.0 found.
2020-12-30 14:23:22.928 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-pipeline-core, Version: 1.19.0 found.
2020-12-30 14:23:22.928 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-train-automl-client, Version: 1.19.0 found.
2020-12-30 14:23:22.929 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: msrestazure, Version: 0.6.4 found.
2020-12-30 14:23:22.929 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: msrest, Version: 0.6.19 found.
2020-12-30 14:23:22.929 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: requests, Version: 2.22.0 found.
2020-12-30 14:23:22.929 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-core, Version: 1.19.0 found.
2020-12-30 14:23:22.929 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: dotnetcore2, Version: 2.1.20 found.
2020-12-30 14:23:22.929 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: cloudpickle, Version: 1.3.0 found.
2020-12-30 14:23:22.930 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-dataprep-native, Version: 26.0.0 found.
2020-12-30 14:23:22.930 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-identity, Version: 1.4.1 found.
2020-12-30 14:23:22.930 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azureml-dataprep-rslex, Version: 1.4.0 found.
2020-12-30 14:23:22.930 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: pyopenssl, Version: 19.1.0 found.
2020-12-30 14:23:22.931 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: pyjwt, Version: 1.7.1 found.
2020-12-30 14:23:22.931 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-mgmt-storage, Version: 11.2.0 found.
2020-12-30 14:23:22.931 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: msrestazure, Version: 0.6.4 found.
2020-12-30 14:23:22.931 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: pathspec, Version: 0.8.1 found.
2020-12-30 14:23:22.931 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: python-dateutil, Version: 2.8.1 found.
2020-12-30 14:23:22.931 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: jsonpickle, Version: 1.4.2 found.
2020-12-30 14:23:22.932 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: cryptography, Version: 2.8 found.
2020-12-30 14:23:22.932 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: adal, Version: 1.2.5 found.
2020-12-30 14:23:22.932 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-common, Version: 1.1.26 found.
2020-12-30 14:23:22.932 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: jmespath, Version: 0.10.0 found.
2020-12-30 14:23:22.932 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: ruamel.yaml, Version: 0.16.12 found.
2020-12-30 14:23:22.932 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: pytz, Version: 2019.3 found.
2020-12-30 14:23:22.932 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: ndg-httpsclient, Version: 0.5.1 found.
2020-12-30 14:23:22.932 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: requests, Version: 2.22.0 found.
2020-12-30 14:23:22.933 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: docker, Version: 4.4.0 found.
2020-12-30 14:23:22.933 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: msrest, Version: 0.6.19 found.
2020-12-30 14:23:22.933 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-graphrbac, Version: 0.61.1 found.
2020-12-30 14:23:22.933 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: urllib3, Version: 1.25.8 found.
2020-12-30 14:23:22.933 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-mgmt-authorization, Version: 0.61.0 found.
2020-12-30 14:23:22.933 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-mgmt-containerregistry, Version: 2.8.0 found.
2020-12-30 14:23:22.933 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: secretstorage, Version: 3.3.0 found.
2020-12-30 14:23:22.933 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: contextlib2, Version: 0.6.0.post1 found.
2020-12-30 14:23:22.934 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-mgmt-keyvault, Version: 2.2.0 found.
2020-12-30 14:23:22.934 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: backports.tempfile, Version: 1.0 found.
2020-12-30 14:23:22.934 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-mgmt-resource, Version: 12.0.0 found.
2020-12-30 14:23:22.936 - INFO - 4032 - azureml.automl.core.package_utilities._get_validated_requirements:361 - Verified requirements file validated_win32_requirements.txt found.
2020-12-30 14:23:29.509 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: adal, Version: 1.2.5 found.
2020-12-30 14:23:29.509 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: applicationinsights, Version: 0.11.9 found.
2020-12-30 14:23:29.509 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-common, Version: 1.1.26 found.
2020-12-30 14:23:29.509 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-core, Version: 1.9.0 found.
2020-12-30 14:23:29.509 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-graphrbac, Version: 0.61.1 found.
2020-12-30 14:23:29.510 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-identity, Version: 1.4.1 found.
2020-12-30 14:23:29.510 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-mgmt-authorization, Version: 0.61.0 found.
2020-12-30 14:23:29.510 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-mgmt-containerregistry, Version: 2.8.0 found.
2020-12-30 14:23:29.510 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-mgmt-keyvault, Version: 2.2.0 found.
2020-12-30 14:23:29.510 - WARNING - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:284 - Package: azure-mgmt-resource, Version: 12.0.0 found.
2020-12-30 14:23:29.510 - ERROR - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:311 - found incompatible requirement azure-mgmt-resource 12.0.0 but expected azure-mgmt-resource<=10.3.0.
2020-12-30 14:23:29.510 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: azure-mgmt-storage, Version: 11.2.0 found.
2020-12-30 14:23:29.510 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package azure-storage-queue missing from working set.
2020-12-30 14:23:29.510 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: backports.tempfile, Version: 1.0 found.
2020-12-30 14:23:29.511 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: backports.weakref, Version: 1.0.post1 found.
2020-12-30 14:23:29.511 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package boto3 missing from working set.
2020-12-30 14:23:29.511 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package botocore missing from working set.
2020-12-30 14:23:29.511 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package configparser missing from working set.
2020-12-30 14:23:29.512 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package dill missing from working set.
2020-12-30 14:23:29.512 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: distro, Version: 1.5.0 found.
2020-12-30 14:23:29.512 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: docker, Version: 4.4.0 found.
2020-12-30 14:23:29.512 - WARNING - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:284 - Package: dotnetcore2, Version: 2.1.20 found.
2020-12-30 14:23:29.512 - ERROR - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:311 - found incompatible requirement dotnetcore2 2.1.20 but expected dotnetcore2<=2.1.19.
2020-12-30 14:23:29.512 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package fire missing from working set.
2020-12-30 14:23:29.512 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: fusepy, Version: 3.0.1 found.
2020-12-30 14:23:29.512 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package gensim missing from working set.
2020-12-30 14:23:29.512 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package gunicorn missing from working set.
2020-12-30 14:23:29.513 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package interpret-community missing from working set.
2020-12-30 14:23:29.513 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package interpret-core missing from working set.
2020-12-30 14:23:29.513 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: isodate, Version: 0.6.0 found.
2020-12-30 14:23:29.514 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: jeepney, Version: 0.6.0 found.
2020-12-30 14:23:29.514 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: jmespath, Version: 0.10.0 found.
2020-12-30 14:23:29.514 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package json-logging-py missing from working set.
2020-12-30 14:23:29.515 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: jsonpickle, Version: 1.4.2 found.
2020-12-30 14:23:29.515 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package keras2onnx missing from working set.
2020-12-30 14:23:29.515 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package liac-arff missing from working set.
2020-12-30 14:23:29.515 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package lightgbm missing from working set.
2020-12-30 14:23:29.516 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: msal-extensions, Version: 0.2.2 found.
2020-12-30 14:23:29.517 - WARNING - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:284 - Package: msal, Version: 1.8.0 found.
2020-12-30 14:23:29.517 - ERROR - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:311 - found incompatible requirement msal 1.8.0 but expected msal<=1.6.0.
2020-12-30 14:23:29.517 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: msrest, Version: 0.6.19 found.
2020-12-30 14:23:29.517 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: msrestazure, Version: 0.6.4 found.
2020-12-30 14:23:29.517 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: ndg-httpsclient, Version: 0.5.1 found.
2020-12-30 14:23:29.518 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package nimbusml missing from working set.
2020-12-30 14:23:29.518 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: oauthlib, Version: 3.1.0 found.
2020-12-30 14:23:29.518 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package onnx missing from working set.
2020-12-30 14:23:29.519 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package onnxconverter-common missing from working set.
2020-12-30 14:23:29.519 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package onnxmltools missing from working set.
2020-12-30 14:23:29.519 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package onnxruntime missing from working set.
2020-12-30 14:23:29.520 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: pathspec, Version: 0.8.1 found.
2020-12-30 14:23:29.520 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package pmdarima missing from working set.
2020-12-30 14:23:29.520 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: portalocker, Version: 1.7.1 found.
2020-12-30 14:23:29.520 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package protobuf missing from working set.
2020-12-30 14:23:29.520 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package py-cpuinfo missing from working set.
2020-12-30 14:23:29.520 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: pyarrow, Version: 1.0.1 found.
2020-12-30 14:23:29.520 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: pyasn1, Version: 0.4.8 found.
2020-12-30 14:23:29.520 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: pyjwt, Version: 1.7.1 found.
2020-12-30 14:23:29.521 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: requests-oauthlib, Version: 1.3.0 found.
2020-12-30 14:23:29.521 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: ruamel.yaml.clib, Version: 0.2.2 found.
2020-12-30 14:23:29.521 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: ruamel.yaml, Version: 0.16.12 found.
2020-12-30 14:23:29.522 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package s3transfer missing from working set.
2020-12-30 14:23:29.522 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: secretstorage, Version: 3.3.0 found.
2020-12-30 14:23:29.522 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package shap missing from working set.
2020-12-30 14:23:29.523 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package skl2onnx missing from working set.
2020-12-30 14:23:29.523 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package sklearn-pandas missing from working set.
2020-12-30 14:23:29.523 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package smart-open missing from working set.
2020-12-30 14:23:29.523 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package termcolor missing from working set.
2020-12-30 14:23:29.524 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:301 - Package typing-extensions missing from working set.
2020-12-30 14:23:29.524 - INFO - 4032 - azureml.automl.core.package_utilities._has_versionconflict_or_not_installed:278 - Package: websocket-client, Version: 0.57.0 found.
2020-12-30 14:23:29.524 - INFO - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:316 - User has the following compatible packages installed:
adal==1.2.5
applicationinsights==0.11.9
azure-common==1.1.26
azure-core==1.9.0
azure-graphrbac==0.61.1
azure-identity==1.4.1
azure-mgmt-authorization==0.61.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-keyvault==2.2.0
azure-mgmt-storage==11.2.0
backports.tempfile==1.0
backports.weakref==1.0.post1
distro==1.5.0
docker==4.4.0
fusepy==3.0.1
isodate==0.6.0
jeepney==0.6.0
jmespath==0.10.0
jsonpickle==1.4.2
msal-extensions==0.2.2
msrest==0.6.19
msrestazure==0.6.4
ndg-httpsclient==0.5.1
oauthlib==3.1.0
pathspec==0.8.1
portalocker==1.7.1
pyarrow==1.0.1
pyasn1==0.4.8
pyjwt==1.7.1
requests-oauthlib==1.3.0
ruamel.yaml.clib==0.2.2
ruamel.yaml==0.16.12
secretstorage==3.3.0
websocket-client==0.57.0
2020-12-30 14:23:29.525 - WARNING - 4032 - azureml.automl.core.package_utilities._get_unverified_dependencies:320 - Skipping package validation check for non pypi packages:
boto==2.49.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
click==7.0
cloudpickle==1.3.0
contextlib2==0.6.0.post1
cryptography==2.8
cython==0.29.15
flask==1.1.1
idna==2.8
importlib-metadata==1.5.0
itsdangerous==1.1.0
jinja2==2.11.1
joblib==0.14.1
markupsafe==1.1.1
numpy==1.18.1
packaging==20.1
pandas==1.0.1
patsy==0.5.1
psutil==5.6.7
pycparser==2.19
pyopenssl==19.1.0
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
pywin32==227
requests==2.22.0
scikit-learn==0.22.1
scipy==1.4.1
six==1.14.0
statsmodels==0.11.0
tqdm==4.42.1
urllib3==1.25.8
werkzeug==1.0.0
zipp==2.2.0
2020-12-30 14:23:29.527 - CRITICAL - 4032 - azureml.automl.core.package_utilities.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ValidationException
Message: ValidationException:
	Message: Install the required versions of packages using the requirements file. Requirements file location: C:\Users\Nandex\anaconda3\lib\site-packages\azureml\automl\core\validated_win32_requirements.txt. Alternatively, use remote target to avoid dependency management. 
Required version/Installed version
azure-mgmt-resource<=10.3.0/azure-mgmt-resource 12.0.0
dotnetcore2<=2.1.19/dotnetcore2 2.1.20
msal<=1.6.0/msal 1.8.0
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Install the required versions of packages using the requirements file. Requirements file location: C:\\Users\\Nandex\\anaconda3\\lib\\site-packages\\azureml\\automl\\core\\validated_win32_requirements.txt. Alternatively, use remote target to avoid dependency management. \nRequired version/Installed version\nazure-mgmt-resource<=10.3.0/azure-mgmt-resource 12.0.0\ndotnetcore2<=2.1.19/dotnetcore2 2.1.20\nmsal<=1.6.0/msal 1.8.0",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "65e7ad52-ad1f-4915-85ad-440d0a5e221f"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "package_utilities.py", line 478, in _get_package_incompatibilities
    validated_requirements_file_path=VALIDATED_REQ_FILE_PATH

ExceptionTarget: Unspecified
2020-12-30 14:23:29.527 - INFO - 4032 - azureml.automl.core.package_utilities._log_activity:92 - ActivityCompleted: Activity=PackagesCheck, HowEnded=Failure, Duration=6635.6[ms]
2020-12-30 16:39:16.530 - INFO - 4032 - azureml.train.automl.automlconfig._start_execution:207 - Submitting remote.
2020-12-30 17:43:46.571 - INFO - 4032 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2020-12-30 17:43:46.594 - INFO - 4032 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2020-12-30 17:43:46.599 - INFO - 4032 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2020-12-30 17:43:47.896 - CRITICAL - 4032 - azureml.train.automl.run.log_traceback:224 - Type: Unclassified
Class: UserErrorException
Message: UserErrorException:
	Message: 
Operation returned an invalid status code 'Forbidden'. The possible reason could be:
1. You are not authorized to access this resource, or directory listing denied.
2. you may not login your azure service, or use other subscription, you can check your
default account by running azure cli commend:
'az account list -o table'.
3. You have multiple objects/login session opened, please close all session and try again.
                
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "\nOperation returned an invalid status code 'Forbidden'. The possible reason could be:\n1. You are not authorized to access this resource, or directory listing denied.\n2. you may not login your azure service, or use other subscription, you can check your\ndefault account by running azure cli commend:\n'az account list -o table'.\n3. You have multiple objects/login session opened, please close all session and try again.\n                "
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 762, in _get_run_internal
    run_tags = self.get_tags()
  File "run.py", line 1438, in get_tags
    return self._client.get_tags()
  File "run_history_facade.py", line 203, in get_tags
    self.run_dto = self.run.get_run()
  File "run_client.py", line 76, in get_run
    return super(RunClient, self).get_run(self._run_id, **kwargs)
  File "experiment_client.py", line 125, in get_run
    **kwargs)
  File "experiment_client.py", line 265, in _execute_with_experimentid_arguments
    *args, **kwargs)
  File "clientbase.py", line 581, in _execute_with_arguments
    return self._call_api(func, *args_list, **kwargs)
  File "clientbase.py", line 239, in _call_api
    return self._execute_with_base_arguments(func, *args, **kwargs)
  File "clientbase.py", line 328, in _execute_with_base_arguments
    back_off, total_retry, self._logger, func, _noop_reset, *args, **kwargs)
  File "clientbase.py", line 361, in _execute_func_internal
    left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
  File "clientbase.py", line 406, in _handle_retry
    raise_from(UserErrorException(error_msg), error)
  File "<string>", line 3, in raise_from

ExceptionTarget: None
2020-12-30 17:43:47.896 - INFO - 4032 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=1296.69[ms]
2020-12-30 17:43:47.898 - CRITICAL - 4032 - azureml.train.automl.run.log_traceback:224 - Type: Unclassified
Class: UserErrorException
Message: UserErrorException:
	Message: 
Operation returned an invalid status code 'Forbidden'. The possible reason could be:
1. You are not authorized to access this resource, or directory listing denied.
2. you may not login your azure service, or use other subscription, you can check your
default account by running azure cli commend:
'az account list -o table'.
3. You have multiple objects/login session opened, please close all session and try again.
                
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "\nOperation returned an invalid status code 'Forbidden'. The possible reason could be:\n1. You are not authorized to access this resource, or directory listing denied.\n2. you may not login your azure service, or use other subscription, you can check your\ndefault account by running azure cli commend:\n'az account list -o table'.\n3. You have multiple objects/login session opened, please close all session and try again.\n                "
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 618, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 762, in _get_run_internal
    run_tags = self.get_tags()
  File "run.py", line 1438, in get_tags
    return self._client.get_tags()
  File "run_history_facade.py", line 203, in get_tags
    self.run_dto = self.run.get_run()
  File "run_client.py", line 76, in get_run
    return super(RunClient, self).get_run(self._run_id, **kwargs)
  File "experiment_client.py", line 125, in get_run
    **kwargs)
  File "experiment_client.py", line 265, in _execute_with_experimentid_arguments
    *args, **kwargs)
  File "clientbase.py", line 581, in _execute_with_arguments
    return self._call_api(func, *args_list, **kwargs)
  File "clientbase.py", line 239, in _call_api
    return self._execute_with_base_arguments(func, *args, **kwargs)
  File "clientbase.py", line 328, in _execute_with_base_arguments
    back_off, total_retry, self._logger, func, _noop_reset, *args, **kwargs)
  File "clientbase.py", line 361, in _execute_func_internal
    left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
  File "clientbase.py", line 406, in _handle_retry
    raise_from(UserErrorException(error_msg), error)
  File "<string>", line 3, in raise_from

ExceptionTarget: None
2020-12-30 17:43:47.898 - INFO - 4032 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1303.75[ms]
2020-12-30 17:43:47.900 - CRITICAL - 4032 - azureml.train.automl.run.log_traceback:224 - Type: Unclassified
Class: UserErrorException
Message: UserErrorException:
	Message: 
Operation returned an invalid status code 'Forbidden'. The possible reason could be:
1. You are not authorized to access this resource, or directory listing denied.
2. you may not login your azure service, or use other subscription, you can check your
default account by running azure cli commend:
'az account list -o table'.
3. You have multiple objects/login session opened, please close all session and try again.
                
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "\nOperation returned an invalid status code 'Forbidden'. The possible reason could be:\n1. You are not authorized to access this resource, or directory listing denied.\n2. you may not login your azure service, or use other subscription, you can check your\ndefault account by running azure cli commend:\n'az account list -o table'.\n3. You have multiple objects/login session opened, please close all session and try again.\n                "
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 688, in get_output
    activity_name=automl_shared_constants.TelemetryConstants.GET_OUTPUT
  File "run.py", line 618, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 762, in _get_run_internal
    run_tags = self.get_tags()
  File "run.py", line 1438, in get_tags
    return self._client.get_tags()
  File "run_history_facade.py", line 203, in get_tags
    self.run_dto = self.run.get_run()
  File "run_client.py", line 76, in get_run
    return super(RunClient, self).get_run(self._run_id, **kwargs)
  File "experiment_client.py", line 125, in get_run
    **kwargs)
  File "experiment_client.py", line 265, in _execute_with_experimentid_arguments
    *args, **kwargs)
  File "clientbase.py", line 581, in _execute_with_arguments
    return self._call_api(func, *args_list, **kwargs)
  File "clientbase.py", line 239, in _call_api
    return self._execute_with_base_arguments(func, *args, **kwargs)
  File "clientbase.py", line 328, in _execute_with_base_arguments
    back_off, total_retry, self._logger, func, _noop_reset, *args, **kwargs)
  File "clientbase.py", line 361, in _execute_func_internal
    left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
  File "clientbase.py", line 406, in _handle_retry
    raise_from(UserErrorException(error_msg), error)
  File "<string>", line 3, in raise_from

ExceptionTarget: None
2020-12-30 17:43:47.900 - INFO - 4032 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1329.59[ms]
2020-12-30 18:29:27.385 - INFO - 25020 - azureml.train.automl.automlconfig._start_execution:207 - Submitting remote.
2020-12-30 20:06:44.955 - INFO - 25020 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2020-12-30 20:06:44.973 - INFO - 25020 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2020-12-30 20:06:44.988 - INFO - 25020 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2020-12-30 20:06:47.454 - INFO - 25020 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=2466.18[ms]
2020-12-30 20:06:47.454 - INFO - 25020 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=2481.18[ms]
2020-12-30 20:06:47.454 - INFO - 25020 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2020-12-30 20:07:02.521 - CRITICAL - 25020 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: ModuleNotFoundError
Message: No module named 'azureml.train.automl.runtime'
Traceback:
  File "_model_download_utilities.py", line 151, in _load_automl_model
    import azureml.train.automl.runtime

ExceptionTarget: Unspecified
2020-12-30 20:07:02.534 - WARNING - 25020 - azureml.train.automl._model_download_utilities._download_automl_model:97 - The model you attempted to retrieve requires 'azureml-train-automl-runtime' to be installed at '==1.19.0'. Please install 'azureml-train-automl-runtime==1.19.0' (e.g. `pip install azureml-train-automl-runtime==1.19.0`) and then rerun the previous command.
2020-12-30 20:07:02.538 - INFO - 25020 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=15084.43[ms]
2020-12-30 20:07:02.539 - INFO - 25020 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=17584.57[ms]
